spring:
  cloud:
    gateway:
      routes:
        - id: ms1
          uri: http://localhost:8081
          predicates:
            - Path=/ms1**/**
          filters:
            - RewritePath=/(?<segment>.*), /ms1/hello
        - id: ms2
          uri: http://localhost:8082
          predicates:
            - Path=/ms2**/**
          filters:
            - RewritePath=/(?<segment>.*), /ms2/hello

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG